'use strict'

let recipeFinder = https://api.edamam.com/search?q=chicken&from=1&to=10&diet="low-fat"&cuisine type="chinese"&meal type=breakfast&dish type="soup"&time=range&excluded=vinegar;
let api key = '56dc91c65105b03d1c0b7071bb00e762';

//format the function for the parameters for the api call
function formatParams(params){
    const queryItems = Object.keys(params)
    .map(key =>
    )
        return queryItems.join('&');
}